# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/pentium/zjucpu/zjucpu.srcs/sources_1/ip/ClockGen/ClockGen.xci
# IP: The module: 'ClockGen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/pentium/zjucpu/zjucpu.srcs/sources_1/ip/ClockGen/ClockGen_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ClockGen'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/pentium/zjucpu/zjucpu.srcs/sources_1/ip/ClockGen/ClockGen.xdc
# XDC: The top module name and the constraint reference have the same name: 'ClockGen'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/pentium/zjucpu/zjucpu.srcs/sources_1/ip/ClockGen/ClockGen_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'ClockGen'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/pentium/zjucpu/zjucpu.srcs/sources_1/ip/ClockGen/ClockGen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ClockGen'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/pentium/zjucpu/zjucpu.srcs/sources_1/ip/ClockGen/ClockGen.xci
# IP: The module: 'ClockGen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/pentium/zjucpu/zjucpu.srcs/sources_1/ip/ClockGen/ClockGen_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ClockGen'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/pentium/zjucpu/zjucpu.srcs/sources_1/ip/ClockGen/ClockGen.xdc
# XDC: The top module name and the constraint reference have the same name: 'ClockGen'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/pentium/zjucpu/zjucpu.srcs/sources_1/ip/ClockGen/ClockGen_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'ClockGen'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/pentium/zjucpu/zjucpu.srcs/sources_1/ip/ClockGen/ClockGen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ClockGen'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
