# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/SWORD4/DDR.xdc

# XDC: imports/SWORD4/Sword_phy.xdc

# XDC: imports/SWORD4/Sword_pin.xdc

# IP: ip/GraphicVRAM/GraphicVRAM.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==GraphicVRAM || ORIG_REF_NAME==GraphicVRAM} -quiet] -quiet

# XDC: ip/GraphicVRAM/GraphicVRAM_ooc.xdc
