# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/pentium/zjucpu/zjucpu.runs/synth_1/Top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 2
set_param xicom.use_bs_reader 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7k325tffg676-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/pentium/zjucpu/zjucpu.cache/wt [current_project]
set_property parent.project_path /home/pentium/zjucpu/zjucpu.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/pentium/zjucpu/zjucpu.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog /home/pentium/zjucpu/zjucpu.srcs/sources_1/imports/v/CPU/TLBDefines.vh
read_verilog -library xil_defaultlib {
  /home/pentium/zjucpu/zjucpu.srcs/sources_1/imports/v/CPU/ALU.v
  /home/pentium/zjucpu/zjucpu.srcs/sources_1/imports/v/Infrastructure/AntiJitter.v
  /home/pentium/zjucpu/zjucpu.srcs/sources_1/imports/v/Infrastructure/BiosMem.v
  /home/pentium/zjucpu/zjucpu.srcs/sources_1/imports/v/CPU/BranchPredictor.v
  /home/pentium/zjucpu/zjucpu.srcs/sources_1/imports/v/CPUBus.v
  /home/pentium/zjucpu/zjucpu.srcs/sources_1/imports/v/CPUCacheTop.v
  /home/pentium/zjucpu/zjucpu.srcs/sources_1/imports/v/Cache/CacheData.v
  /home/pentium/zjucpu/zjucpu.srcs/sources_1/imports/v/Cache/CacheFlags.v
  /home/pentium/zjucpu/zjucpu.srcs/sources_1/imports/v/Infrastructure/ClockDomainCross.v
  /home/pentium/zjucpu/zjucpu.srcs/sources_1/imports/v/CPU/Cp0.v
  /home/pentium/zjucpu/zjucpu.srcs/sources_1/imports/v/CPU/Cp0Reg.v
  /home/pentium/zjucpu/zjucpu.srcs/sources_1/imports/v/Cache/DCache.v
  /home/pentium/zjucpu/zjucpu.srcs/sources_1/imports/SWORD4/DDR3_wsWrapper.v
  /home/pentium/zjucpu/zjucpu.srcs/sources_1/imports/v/CPU/ExcControl.v
  /home/pentium/zjucpu/zjucpu.srcs/sources_1/imports/v/Infrastructure/FIFO.v
  /home/pentium/zjucpu/zjucpu.srcs/sources_1/imports/v/CPU/FwdUnit.v
  /home/pentium/zjucpu/zjucpu.srcs/sources_1/imports/v/Cache/ICache.v
  /home/pentium/zjucpu/zjucpu.srcs/sources_1/imports/SWORD4/Infrastructure_Sword.v
  /home/pentium/zjucpu/zjucpu.srcs/sources_1/imports/v/CPU/InstDecoder.v
  /home/pentium/zjucpu/zjucpu.srcs/sources_1/imports/SWORD4/Keypad.v
  /home/pentium/zjucpu/zjucpu.srcs/sources_1/imports/v/CPU/MulDiv.v
  /home/pentium/zjucpu/zjucpu.srcs/sources_1/imports/v/CPU/PCPU.v
  /home/pentium/zjucpu/zjucpu.srcs/sources_1/imports/v/Infrastructure/PS2Driver.v
  /home/pentium/zjucpu/zjucpu.srcs/sources_1/imports/v/Infrastructure/PS2Wrapper.v
  /home/pentium/zjucpu/zjucpu.srcs/sources_1/imports/v/CPU/Regs.v
  /home/pentium/zjucpu/zjucpu.srcs/sources_1/imports/v/Infrastructure/ReprogInterface.v
  /home/pentium/zjucpu/zjucpu.srcs/sources_1/imports/v/SD/SDC_CRC.v
  /home/pentium/zjucpu/zjucpu.srcs/sources_1/imports/v/SD/SDC_Clocking.v
  /home/pentium/zjucpu/zjucpu.srcs/sources_1/imports/v/SD/SDC_Cmdpath.v
  /home/pentium/zjucpu/zjucpu.srcs/sources_1/imports/v/SD/SDC_DMA.v
  /home/pentium/zjucpu/zjucpu.srcs/sources_1/imports/v/SD/SDC_DataReceiver.v
  /home/pentium/zjucpu/zjucpu.srcs/sources_1/imports/v/SD/SDC_DataTransmitter.v
  /home/pentium/zjucpu/zjucpu.srcs/sources_1/imports/v/SD/SDC_Datapath.v
  /home/pentium/zjucpu/zjucpu.srcs/sources_1/imports/v/SD/SDC_Registers.v
  /home/pentium/zjucpu/zjucpu.srcs/sources_1/imports/v/SD/SDC_RxUpscaler.v
  /home/pentium/zjucpu/zjucpu.srcs/sources_1/imports/v/SD/SDC_TxDownscaler.v
  /home/pentium/zjucpu/zjucpu.srcs/sources_1/imports/v/SD/SDController.v
  /home/pentium/zjucpu/zjucpu.srcs/sources_1/imports/v/SD/SDWrapper.v
  /home/pentium/zjucpu/zjucpu.srcs/sources_1/imports/SWORD4/Seg7Device.v
  /home/pentium/zjucpu/zjucpu.srcs/sources_1/imports/SWORD4/ShiftReg.v
  /home/pentium/zjucpu/zjucpu.srcs/sources_1/imports/v/CPU/StageID.v
  /home/pentium/zjucpu/zjucpu.srcs/sources_1/imports/v/CPU/StageMem.v
  /home/pentium/zjucpu/zjucpu.srcs/sources_1/imports/v/CPU/TLB.v
  /home/pentium/zjucpu/zjucpu.srcs/sources_1/imports/v/CPU/TLBEntry.v
  /home/pentium/zjucpu/zjucpu.srcs/sources_1/imports/v/CPU/TLBHeader.v
  /home/pentium/zjucpu/zjucpu.srcs/sources_1/imports/v/CPU/TLBRNG.v
  /home/pentium/zjucpu/zjucpu.srcs/sources_1/imports/v/CPU/TranslatePredict.v
  /home/pentium/zjucpu/zjucpu.srcs/sources_1/imports/v/Infrastructure/UART.v
  /home/pentium/zjucpu/zjucpu.srcs/sources_1/imports/v/Infrastructure/UARTWrapper.v
  /home/pentium/zjucpu/zjucpu.srcs/sources_1/imports/v/Infrastructure/VGADevice.v
  /home/pentium/zjucpu/zjucpu.srcs/sources_1/imports/v/Infrastructure/VGAScan.v
  /home/pentium/zjucpu/zjucpu.srcs/sources_1/imports/v/Infrastructure/VRAM.v
  /home/pentium/zjucpu/zjucpu.srcs/sources_1/imports/v/CPU/divider.v
  /home/pentium/zjucpu/zjucpu.srcs/sources_1/imports/v/CPU/stageEX.v
  /home/pentium/zjucpu/zjucpu.srcs/sources_1/imports/SWORD4/Top.v
}
read_ip -quiet /home/pentium/zjucpu/zjucpu.srcs/sources_1/ip/GraphicVRAM/GraphicVRAM.xci
set_property used_in_implementation false [get_files -all /home/pentium/zjucpu/zjucpu.srcs/sources_1/ip/GraphicVRAM/GraphicVRAM_ooc.xdc]

read_ip -quiet /home/pentium/zjucpu/zjucpu.srcs/sources_1/ip/DDR3/DDR3.xci
set_property used_in_implementation false [get_files -all /home/pentium/zjucpu/zjucpu.gen/sources_1/ip/DDR3/DDR3/user_design/constraints/DDR3.xdc]
set_property used_in_implementation false [get_files -all /home/pentium/zjucpu/zjucpu.gen/sources_1/ip/DDR3/DDR3/user_design/constraints/DDR3_ooc.xdc]

read_ip -quiet /home/pentium/zjucpu/zjucpu.srcs/sources_1/ip/ClockGen/ClockGen.xci
set_property used_in_implementation false [get_files -all /home/pentium/zjucpu/zjucpu.srcs/sources_1/ip/ClockGen/ClockGen_board.xdc]
set_property used_in_implementation false [get_files -all /home/pentium/zjucpu/zjucpu.srcs/sources_1/ip/ClockGen/ClockGen.xdc]
set_property used_in_implementation false [get_files -all /home/pentium/zjucpu/zjucpu.srcs/sources_1/ip/ClockGen/ClockGen_late.xdc]
set_property used_in_implementation false [get_files -all /home/pentium/zjucpu/zjucpu.srcs/sources_1/ip/ClockGen/ClockGen_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/pentium/zjucpu/zjucpu.srcs/constrs_1/imports/SWORD4/DDR.xdc
set_property used_in_implementation false [get_files /home/pentium/zjucpu/zjucpu.srcs/constrs_1/imports/SWORD4/DDR.xdc]

read_xdc /home/pentium/zjucpu/zjucpu.srcs/constrs_1/imports/SWORD4/Sword_phy.xdc
set_property used_in_implementation false [get_files /home/pentium/zjucpu/zjucpu.srcs/constrs_1/imports/SWORD4/Sword_phy.xdc]

read_xdc /home/pentium/zjucpu/zjucpu.srcs/constrs_1/imports/SWORD4/Sword_pin.xdc
set_property used_in_implementation false [get_files /home/pentium/zjucpu/zjucpu.srcs/constrs_1/imports/SWORD4/Sword_pin.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top Top -part xc7k325tffg676-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Top_utilization_synth.rpt -pb Top_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
